### ISSUE TITLE
pysaml2 version 4.5 not working with python version 2.7.5

### ISSUE THREAD

**Issue by wpr101** [rohe/pysaml2#470] opened 2017-10-26 20:19 UTC
Hello, the system I am running on uses Python 2.7.5. We have a build script which does a pip install of the latest version of pysaml2. 

Recently, the version 4.5 broke because of signature mismatches. We hard coded the install to be for version 4.4.0 and our code ran fine again.

Any idea if version 4.5 will work with python 2.7.5? Do we need to upgrade to python 2.7.14 to get it to work?

Thank you.

**Comment by c00kiemon5ter** [comment] 2017-10-28 16:24
Hello, 

I think your setup broke because of commit 46d24f6af561d75d455f7b73e5a3d19837d32d2f (see #424 and #439). The commit changes the default value for `want_response_signed` from `False` to `True`. 

Try [setting the configuration value](https://github.com/rohe/pysaml2/blob/d8eef64ebe54989f577a1e48eb78787b0dd8db41/doc/howto/config.rst#want_response_signed) to `False` and try again. 

@rohe @jkakavas this should probably have been part of the release notes

**Comment by c00kiemon5ter** [comment] 2017-11-15 11:30
I am closing this, but if there is more feedback and the issue is not solved by the above setting, do not hesitate to reopen this. 

Thanks

**Closed by c00kiemon5ter** 2017-11-15 11:30 UTC
