### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by nbartos** [rohe/pysaml2#452] opened 2017-09-11 00:40 UTC
The latest 4.4.0 pypi package (nearly a year old) has bugs that affect us, and they are fixed in master.  Could you please cut a new pypi release from master?  Thanks!

**Comment by jkakavas** [comment] 2017-09-11 07:11
Duplicate of #435

**Comment by c00kiemon5ter** [comment] 2017-11-15 11:12
pysaml2 version 4.5.0 has been released. This can now be closed.

**Closed** 2017-11-15 11:13 UTC
Labels: duplicate
